#!/bin/bash

# Drift Notification Script
# This script is called when drift is detected in the Terraform infrastructure
# It sends an email notification with details about the detected drift
# and includes links to approve or reject the changes

# Configuration
RECIPIENT_EMAIL="${1:-devops@example.com}"  # Default email if not provided as argument
SUBJECT="Terraform Drift Detected - Manual Approval Required"
PLAN_FILE="${2:-plan.out}"  # Plan file path, default to plan.out
APPROVAL_URL="${3:-https://todoforge.mooo.com/approve}"  # Replace with your actual approval endpoint
REJECT_URL="${4:-https://todoforge.mooo.com/reject}"    # Replace with your actual reject endpoint

# Check if plan file exists
if [ ! -f "$PLAN_FILE" ]; then
    echo "Error: Plan file $PLAN_FILE not found"
    exit 1
fi

# Extract plan output
PLAN_OUTPUT=$(terraform show -no-color "$PLAN_FILE")

# Create a temporary file for the email body
EMAIL_BODY=$(mktemp)

# Write email body to the temporary file
cat << EOF > "$EMAIL_BODY"
Terraform drift has been detected in your infrastructure.

Plan Output:
$PLAN_OUTPUT

Please review the changes and take action:

Approve Changes: $APPROVAL_URL
Reject Changes: $REJECT_URL

The CI/CD pipeline will wait for your approval before proceeding.

This notification was generated by the drift detection system.
EOF

# Function to send email using sendmail
send_email_sendmail() {
    (
        echo "Subject: $SUBJECT"
        echo "To: $RECIPIENT_EMAIL"
        echo "From: terraform-drift-detection@example.com"
        echo "Content-Type: text/plain; charset=UTF-8"
        echo ""
        cat "$EMAIL_BODY"
    ) | sendmail -t
}

# Function to send email using mail command
send_email_mail() {
    mail -s "$SUBJECT" -r "terraform-drift-detection@example.com" "$RECIPIENT_EMAIL" < "$EMAIL_BODY"
}

# Function to send email using AWS SES (requires AWS CLI)
send_email_ses() {
    aws ses send-email \
        --from "terraform-drift-detection@example.com" \
        --destination "ToAddresses=$RECIPIENT_EMAIL" \
        --message "Subject={Data=$SUBJECT,Charset=utf-8},Body={Text={Data=$(cat "$EMAIL_BODY"),Charset=utf-8}}"
}

# Try to send email using different methods
if command -v sendmail &> /dev/null; then
    echo "Sending email using sendmail..."
    send_email_sendmail
    if [ $? -eq 0 ]; then
        echo "Email sent successfully using sendmail"
    else
        echo "Failed to send email using sendmail"
    fi
elif command -v mail &> /dev/null; then
    echo "Sending email using mail command..."
    send_email_mail
    if [ $? -eq 0 ]; then
        echo "Email sent successfully using mail command"
    else
        echo "Failed to send email using mail command"
    fi
elif command -v aws &> /dev/null; then
    echo "Sending email using AWS SES..."
    send_email_ses
    if [ $? -eq 0 ]; then
        echo "Email sent successfully using AWS SES"
    else
        echo "Failed to send email using AWS SES"
    fi
else
    echo "Error: No email sending method available. Please install sendmail, mail, or AWS CLI."
    exit 1
fi

# Clean up
rm -f "$EMAIL_BODY"

# Log the drift detection event
echo "$(date): Drift detected and notification sent to $RECIPIENT_EMAIL" >> /var/log/terraform-drift-detection.log

# Exit with a special code to indicate that manual approval is needed
# This can be used by CI/CD pipelines to pause and wait for approval
exit 100